# Generated by Django 2.0.2 on 2019-07-11 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20190711_1032'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='imagefile',
            new_name='image',
        ),
    ]
